name: oureschoolweb
description: Web Part of Our-E-School App
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  responsive_framework: ^0.0.7
  google_fonts: ^0.3.9
  #state management
  stacked: ^1.4.1+2
  #Inversion of control
  #It means removing dependencies from your code by getting them from somewhere else or injecting them into your code
  get_it: ^4.0.2
  injectable: ^0.3.0
  #Navigation
  auto_route: ^0.4.5
  stacked_services: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^0.4.8
  build_runner: ^1.9.0
  injectable_generator: ^0.3.5

dependency_overrides:
  get: ^2.0.9-dev

flutter:
  uses-material-design: true
  assets:
    - assets/
